name: Snapshot Build Java CI with Gradle

on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:


jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Add permissons
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -PsnapshotBuild=true -Xtest

      - name: Upload Snapshot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs